<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'FaDoe\Filter\IniBoolean' => __DIR__ . '/src/FaDoe/Filter/IniBoolean.php',
    'FaDoe\Filter\ByteSize'   => __DIR__ . '/src/FaDoe/Filter/ByteSize.php',
);
